use program2;
SELECT SALESMAN_ID, NAME FROM
SALESMAN A
WHERE 1 < (SELECT COUNT(*) FROM
CUSTOMER
WHERE SALESMAN_ID=A.SALESMAN_ID);

insert into customer values(5555, 'TCS', 2 , 'bangalore',1000);

UPDATE Customer
SET city = 'mumbai', salesman_id= 2000
WHERE customer_id = 4444;

CREATE VIEW sales1_SALESMAN AS
SELECT B.ORD_DATE, A.SALESMAN_ID, A.NAME, B.purchase_amt FROM
SALESMAN A, ORDERS B
WHERE A.SALESMAN_ID = B.SALESMAN_ID
AND B.PURCHASE_AMT=(SELECT MAX(PURCHASE_AMT)
FROM ORDERS C
WHERE C.ORD_DATE = '2020-12-23');

select * from sales1_SALESMAN;


SELECT SALESMAN.SALESMAN_ID, NAME, CUST_NAME, COMMISSION FROM
SALESMAN, CUSTOMER
WHERE SALESMAN.CITY = CUSTOMER.CITY
UNION
SELECT SALESMAN_ID, NAME, 'NO MATCH', COMMISSION
FROM SALESMAN
WHERE NOT CITY = ANY
(SELECT CITY
FROM CUSTOMER)
ORDER BY 2 DESC;

DELETE FROM SALESMAN WHERE
SALESMAN_ID=1000;